# Generated by Django 3.2.5 on 2022-04-08 05:59

import contentcuration.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0137_auto_20220405_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentnode',
            name='screen_reader',
        ),
        migrations.CreateModel(
            name='ContentScreenReader',
            fields=[
                ('id', contentcuration.models.UUIDField(default=uuid.uuid4, max_length=32, primary_key=True, serialize=False)),
                ('screen_reader_name', models.CharField(max_length=50)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screen_reader', to='contentcuration.channel')),
            ],
            options={
                'unique_together': {('screen_reader_name', 'channel')},
            },
        ),
        migrations.AddField(
            model_name='contentnode',
            name='screen_reader',
            field=models.ManyToManyField(blank=True, related_name='screen_reader_content', to='contentcuration.ContentScreenReader'),
        ),
    ]
