# Generated by Django 3.2.5 on 2022-04-08 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0138_auto_20220408_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentscreenreader',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screen_readers', to='contentcuration.channel'),
        ),
    ]
