# Generated by Django 3.2.5 on 2022-05-13 10:35

import contentcuration.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contentcuration', '0140_auto_20220410_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentscreenreader',
            old_name='readers_name',
            new_name='reader_name',
        ),
        migrations.RemoveField(
            model_name='contentnode',
            name='osValidators',
        ),
        migrations.AlterField(
            model_name='contentnode',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='content_readers', to='contentcuration.ContentScreenReader'),
        ),
        migrations.AlterField(
            model_name='contentscreenreader',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readers', to='contentcuration.channel'),
        ),
        migrations.AlterUniqueTogether(
            name='contentscreenreader',
            unique_together={('reader_name', 'channel')},
        ),
        migrations.CreateModel(
            name='ContentOsValidator',
            fields=[
                ('id', contentcuration.models.UUIDField(default=uuid.uuid4, max_length=32, primary_key=True, serialize=False)),
                ('osvalidator_name', models.CharField(max_length=50)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osvalidators', to='contentcuration.channel')),
            ],
            options={
                'unique_together': {('osvalidator_name', 'channel')},
            },
        ),
        migrations.AddField(
            model_name='contentnode',
            name='osvalidators',
            field=models.ManyToManyField(blank=True, related_name='content_osvalidators', to='contentcuration.ContentOsValidator'),
        ),
    ]
